### ISSUE TITLE
Unable to create session

### ISSUE THREAD

**Issue by fountainheadpro** [lightning-viz/lightning-scala#18]
val lgn = Lightning(host = "http://boot2docker:3000/")
lgn.createSession("word-cloud")
org.json4s.ParserUtil$ParseException: unknown token <
Near: <
    at org.json4s.native.JsonParser$Parser.fail(JsonParser.scala:207)
    at org.json4s.native.JsonParser$Parser.nextToken(JsonParser.scala:294)
    at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:159)
    at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:117)
    at org.json4s.native.JsonParser$.parse(JsonParser.scala:105)
    at org.json4s.native.JsonParser$.parse(JsonParser.scala:53)
    at org.json4s.native.JsonMethods$class.parse(JsonMethods.scala:11)
    at org.json4s.native.JsonMethods$.parse(JsonMethods.scala:61)
    at org.viz.lightning.Lightning.post(Lightning.scala:87)
    at org.viz.lightning.Lightning.createSession(Lightning.scala:29)
    at .<init>(<console>:12)
    at .<clinit>(<console>)
    at .<init>(<console>:7)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
    at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
    at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
    at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
    at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
    at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
    at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
    at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
    at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
    at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
    at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76)
    at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
    at sbt.Logger$$anon$4.apply(Logger.scala:85)
    at sbt.TrapExit$App.run(TrapExit.scala:248)
    at java.lang.Thread.run(Thread.java:745)

**Comment by AdrianP-** [comment]
Try to remove the last "/" in this way: 

val lgn = Lightning(host = "http://boot2docker:3000")

**Comment by carsonpun** [comment]
I ran into the same issue before. But I resolved and able to plot by confirming the 
scala REPL is the same version of the lightning jar created through `sbt assembly` (this is very important)

In my original failed case, my scala REPL is 2.11.6 but the jar is in 2.10.x after move all of them to 2.11.6 I can do the plotting.

**Comment by carsonpun** [comment]
I ran into the same issue before. But I resolved and able to plot by confirming the 
scala REPL is the same version of the lightning jar created through sbt assembly (this is very important)

In my original failed case, my scala REPL was 2.11.6 but the jar was in 2.10.x after moved all of them to 2.11.6 I can perform the plotting.

**Comment by ucrkarthik** [comment]
So how did you move the lightning-scala project to 2.11.6? Did you just update the scalaVersion value to "2.11.6" in the build.sbt file and run "sbt assembly" to create a new assembly jar? Did you have to update any other artifact jar versions?

**Comment by carsonpun** [comment]
I only changed the `build.sbt` for the followings:
from:
`scalaVersion := "2.10.3"`
to:
`scalaVersion := "2.11.6"`

**Comment by ucrkarthik** [comment]
I am still working on getting the error fixed with a local instance of Jupyter Server. I am getting lots of crazy errors when I start Jupyter Server. So, I decided to just use the public Jupyter Server(http://public.lightning-viz.org). 

I was able to run the example code in Jypter(Apache Toree Scala Kernel) but where's the visualizations(Screen shot below)? 

![screen shot 2016-04-07 at 9 38 34 am](https://cloud.githubusercontent.com/assets/3776926/14359049/8d70a9e8-fca4-11e5-851b-13da0e3463d4.png)
